name: webapp 

on:
  workflow_dispatch:
    inputs:
      orgName:
        description: 'Enter your Azure DevOps Organization name'
        required: true
      projectName:
        description: 'Enter your Azure DevOps Project name'
        required: true
      azure-pipeline-name:
        description: 'Enter the azure-pipeline-name'
        required: true
        default: 'create_vm'
      ResourceYamlFile:
        description: 'Select the resource YAML file'
        required: true
      Resourcegroup:
        description: 'Select the Resourcegroup'
        required: true
      app_service_plan_name:
        description: 'app_service_plan_name'
        required: true
      web_app_name:
        description: 'web_app_name'
        required: true

jobs:
  # Display input values for debugging
  display-input-values:
    runs-on: ubuntu-latest
    steps:
      - name: Display Input Values
        run: |
          echo "orgName: ${{ github.event.inputs.orgName }}"
          echo "projectname: ${{ github.event.inputs.projectName }}"
          echo "ResourceYamlFile: ${{ github.event.inputs.ResourceYamlFile }}"
          echo "azure-pipeline-name: ${{ github.event.inputs.azure-pipeline-name }}"
          echo "Resourcegroup: ${{ github.event.inputs.Resourcegroup }}"
          echo "app_service_plan_name: ${{ github.event.inputs['app_service_plan_name'] }}"
          echo "web_app_name: ${{ github.event.inputs['web_app_name'] }}"

  build-in-actions-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Azure Login using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Trigger an Existing Azure Pipeline to deploy the app to PRODUCTION
        uses: Azure/pipelines@releases/v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/${{ github.event.inputs.orgName }}/${{ github.event.inputs.projectName }}'
          azure-pipeline-name: ${{ github.event.inputs.azure-pipeline-name }}  # Use your existing pipeline name here
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          parameters: |
            {
              "ResourceYamlFile": "${{ github.event.inputs.ResourceYamlFile }}",
              "Resourcegroup": "${{ github.event.inputs.Resourcegroup }}",
              "app_service_plan_name": "${{ github.event.inputs.app_service_plan_name }}",
              "web_app_name": "${{ github.event.inputs.web_app_name }}"
            }
